### ISSUE TITLE
Update for Capistrano 3?

### ISSUE THREAD

**Issue by davidham** [markjaquith/WP-Stack#26]
Are there any plans to update this to use Capistrano 3.x?

**Comment by mikelittle** [comment]
Mark, 
Are there any current plans to bring this up to date? It seems the current deploy scripts don't work with a fresh install of Capistrano. I found a number of articles attempting to address this and similar issues, but they seemed old and not applicable to the current releases. My Ruby knowledge is non-existent, so I wasn't able to apply the old solutions to the current problems.

**Comment by mathieuhays** [comment]
If you want the current version to work you can install capistrano v2.15.5 : 
```
sudo gem install capistrano -v 2.15.5
sudo gem install capistrano-ext railsless-deploy
```

If you want to use Capistrano 3, there is this repo : https://github.com/Mixd/wp-deploy. I haven't tried it but it seems to provide a similar logic.
